- name: Deploy to Heroku
  # You may pin to the exact commit or the version.
  # uses: AkhileshNS/heroku-deploy@2b2cf430a1f428bcf8936ba946fe846baa6eba02
  uses: AkhileshNS/heroku-deploy@v3.10.9
  with:
    # This will be used for authentication. You can find it in your heroku homepage account settings
    heroku_api_key: 
    # Email that you use with heroku
    heroku_email: 
    # The appname to use for deploying/updating
    heroku_app_name: 
    # An optional buildpack to use when creating the heroku application
    buildpack: # optional
    # The branch that you would like to deploy to Heroku
    branch: # optional, default is HEAD
    # Set this to true if you don't want to use --force when switching branches
    dontuseforce: # optional, default is false
    # Set this to true if you don't want to automatically create the Heroku app
    dontautocreate: # optional, default is false
    # Will deploy using Dockerfile in project root.
    usedocker: # optional, default is false
    # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
    docker_heroku_process_type: # optional, default is web
    # A list of args to pass into the Docker build. This option only makes sense when usedocker enabled
    docker_build_args: # optional
    # Set if your app is located in a subdirectory.
    appdir: # optional, default is 
    # A URL to which a healthcheck is performed (checks for 200 request)
    healthcheck: # optional, default is 
    # Value to check for when conducting healthcheck request
    checkstring: # optional, default is 
    # Time (in seconds) to wait before performing healthcheck
    delay: # optional, default is 0
    # Contents of the Procfile to save and deploy
    procfile: # optional, default is 
    # When set to true this will attempt to rollback to the previous release if the healthcheck fails
    rollbackonhealthcheckfailed: # optional, default is false
    # Path to an localized env file
    env_file: # optional, default is 
    # Set to true if you want the action to just login to Heroku and nothing else
    justlogin: # optional, default is false
    # The region in which you would like to deploy a server
    region: # optional, default is 
    # If deploying to an organization, then specify the name of the team or organization here
    team: # optional, default is 
    # The remote branch to which you would like to push
    remote_branch: # optional, default is main
    heroku buildpacks:set heroku/java
